### ISSUE TITLE
Do you support the latest yolov5-7.0 seg?

### ISSUE THREAD

**Issue by xiaocode337317439** [Hyuto/yolov5-tfjs#4]
Do you support the latest yolov5-7.0 seg?

**Comment by Hyuto** [comment]
Hello, 

Currently the app support all Object Detection model from YOLOv5. As for Object Segmentation on YOLOv5 latest release (v7.0) isn't supported, maybe I'll create new repo for that in the future but now YOLOv5-seg doesn't support `tensorflow` model to export yet (onnx and tensorrt only)

**Comment by Hyuto** [comment]
Hello just a little bit update here, I've implemented it using onnxruntime-web although the performance is bad and can't do live detection (video), but hey IT WORKS 😁 

https://github.com/Hyuto/yolov5-seg-onnxruntime-web
